### ISSUE TITLE
`Parser.RotateLeft` is unintuitive

### ISSUE THREAD

**Issue by ianlewis** [ianlewis/lexparse#51]
`Parser.RotateLeft` "rotates" the current node to the position of it's parent but the parent then just gets appended to the children of the current node. This results in the previous parent being on the rightmost child position of the current node even though this is a left rotation.

Before left rotation of A2:
```mermaid
graph TD;
    A-->A1;
    A-->A2;
    A2-->A2-1;
    A2-->A2-2;
```

After left rotation of A2:
```mermaid
graph TD;
    A2-->A2-1;
    A2-->A2-2;
    A2-->A;
    A-->A1;
```

I would expect it to result in this tree:
```mermaid
graph TD;
    A2-->A;
    A2-->A2-1;
    A2-->A2-2;
    A-->A1;
```

**Comment by ianlewis** [comment]
@superfrink Could you explain a bit more about the use case when you created this?

**Comment by superfrink** [comment]
Agreed, the diagram would be expected to look like you show.  🤔 

`RotateLeft` was used in an example calculator program that did not make it into a PR.  It was used to manipulate the tree to support order-of-operations.
https://github.com/superfrink/lexparse/blob/231231-example-calc/examples/calc/calc.go

`RotateLeft` has a couple small differences between that branch and the main branch but they look like don't change the shape of the tree.  (Error checking and the case where the root node needs to be updated.)

If the tree is not as expected then it seems like it should be possible to write a test case where the calculator does not work.

**Comment by superfrink** [comment]
On input `1 + 2 + 3` the steps of the parsing look like

Read `1`:

```mermaid
graph TD;
    1;
```

Read `+`:

```mermaid
graph TD;
    1-->+;
```

Rotate so `+` is the parent of `1`:

```mermaid
graph TD;
    +-->1;
```

Read `2`:

```mermaid
graph TD;
    +-->1;
    +-->2;
```

On input `1 * 2 + 3` after reading `+` and before `RotateLeft` it looks like:

```mermaid
graph TD;
    *-->1;
    *-->2;
    *-->+;
```

After `RotateLeft` it looks like this:

```mermaid
graph TD;
    +-->*;
    *-->1;
    *-->2;
```

And then after reading the `3` it looks like this.  Oh, no this isn't correct.  Mermaid is moving the `3` to look like the first child.  The `3` is the second child of `+`.

```mermaid
graph TD;
    +-->*;
    *-->1;
    *-->2;
    +-->3;
```

This is the output from `printTreeNodes(0, tree.Root)` in `calc.go`:
```
 [*lexparse.Node[main.calcToken]] Value: [main.calcToken]  {Type:0 Value:}
  [*lexparse.Node[main.calcToken]] Value: [main.calcToken]  {Type:2 Value:+}
   [*lexparse.Node[main.calcToken]] Value: [main.calcToken]  {Type:1 Value:*}
    [*lexparse.Node[main.calcToken]] Value: [main.calcToken]  {Type:3 Value:1}
    [*lexparse.Node[main.calcToken]] Value: [main.calcToken]  {Type:3 Value:2}
   [*lexparse.Node[main.calcToken]] Value: [main.calcToken]  {Type:3 Value:3}
```

**Comment by ianlewis** [comment]
@superfrink Ok, I think we're mostly on the same page. I was actually implementing an example calculator on #36 very similar to your example here and I ran into this when trying to use `RotateLeft`. I'll see if I can prepare a concrete change that makes sense and ask you to review the PR.

**Comment by ianlewis** [comment]
> Oh, no this isn't correct. Mermaid is moving the `3` to look like the first child. The `3` is the second child of `+`.

Seems like this has been a long standing issue in Mermaid -> https://github.com/mermaid-js/mermaid/issues/815

**Comment by superfrink** [comment]
The existing `RotateLeft` could be better named something like `BecomeParentOfParent` or `MoveUpTree` or `AdoptParent`.  Or maybe there is a better pattern than doing it this way.

**Comment by ianlewis** [comment]
Is there a reason to keep the current implementation? I don't think we really need to worry about backwards compatibility.

**Comment by superfrink** [comment]
We don't need to keep `RotateLeft`.  The only place it was used was in that example calculator (and it was never merged).
